# Generated by Django 5.2.5 on 2025-10-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('role', models.CharField(max_length=100)),
                ('extracted_skills', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
