# Generated by Django 5.2.5 on 2025-10-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='recommended_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='role',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
