# Generated by Django 5.2.5 on 2025-10-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='file',
        ),
        migrations.AddField(
            model_name='resume',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
